{
 "title": "Executor AVS",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Executor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Executor Current Balance (ETH)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "executor_native_token_current_balance{}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Native token spent (ETH)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "sum(executor_native_token_spent_amount{job=\"operator\"})) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executed workflows",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(executor_executed_workflows_amount_total{job=\"operator\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors Amount",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(executor_errors_total{job=\"operator\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Executor Resouces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(executor_operator_cpu_usage{job=\"operator\"}[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Total Allocated), MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 10 },
   "targets": [
    {
     "expr": "max(go_memstats_alloc_bytes{job=\"operator\"} / (1024*1024)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Total Obtained from OS), MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 10 },
   "targets": [
    {
     "expr": "max(go_memstats_sys_bytes{job=\"operator\"} / (1024*1024)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}