{
 "title": "New dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Executor Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Processing Iteration Seconds",
   "type": "timeseries",
   "description": "Duration of a single processing iteration in seconds",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(executor_block_processing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(executor_block_processing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(executor_block_processing_duration_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  {
   "title": "Workflows Total",
   "type": "timeseries",
   "description": "Executed and sent workflows amount",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(executor_sent_workflows_total{}[$__rate_interval])) ",
     "legendFormat": "sent (overall per-second rate)"
    },
    {
     "expr": "sum(rate(executor_executed_workflows_total{}[$__rate_interval]))",
     "legendFormat": "executed (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Current Native Token Balance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg(executor_native_token_current_balance{}) by (job)",
     "legendFormat": "{{job}} (average)"
    }
   ]
  },
  {
   "title": "Native Token Spent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(executor_native_token_spent_total{}[$__rate_interval])) by (job)",
     "legendFormat": "{{job}} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(executor_errors_total{}[$__rate_interval]))",
     "legendFormat": "${metric} (overall per-second rate)"
    }
   ]
  },
  {
   "title": "Block Mining Seconds",
   "type": "timeseries",
   "description": "Duration from mempool inclusion to block mining",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(executor_mining_latency_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(executor_mining_latency_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "90th Percentile"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(executor_mining_latency_seconds_bucket{}[$__rate_interval])))",
     "legendFormat": "50th Percentile"
    }
   ]
  },
  { "title": "Executor Resouces", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "New Panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "avg(go_memstats_alloc_bytes{})", "legendFormat": "${metric} (average)" }
   ]
  },
  {
   "title": "Memory (Total Obtained from OS), MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "max(go_memstats_sys_bytes{job=\"ditto-operator\"} / (1024*1024)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory (Total Allocated), MB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "targets": [
    {
     "expr": "max(go_memstats_alloc_bytes{job=\"ditto-operator\"} / (1024*1024)) by (job)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}