version: '3.7'

services:
  app:
    container_name: operator
    build: 
      context: ../
      args:
        - APP=operator
    restart: on-failure
    ports:
      - 8080:8080
      - 7070:7070
    command: ["run", 
              "--node-url", "wss://silent-tame-seed.ethereum-holesky.quiknode.pro/a09b2aafbc9447b172c9964f3ac40c85edf5fd6a", 
              "--contract-addr", "0xA1554918d4C6Ee86BDfA45a94937565FD3C35D00"]

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
