name: Build Image

on:
  workflow_call:
    inputs:
      APP:
        required: true
        type: string
        description: Application that is supposed to be built and used as the entrypoint for the image.

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Build image
        uses: docker/build-push-action@v5
        with:
          tags: ditto-operator-avs:latest
          load: true # Loads the image into Docker daemon
          build-args: |
            APP=${{ inputs.APP }}
          secrets: |
            CI_GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}

      - name: Save Docker image
        run: docker save ditto-operator-avs:latest | gzip > image.tar.gz

      # To load run `gunzip -c image.tar.gz | docker load`
      - name: Upload Docker image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: image
          path: image.tar.gz
