name: Reusable Testing Workflow

on:
  workflow_call:
    inputs:
      go_version:
        type: string
        default: '1.22'
      lint_timeout:
        type: string
        default: '5m'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - uses: actions/checkout@v4
      - run: make build

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ inputs.go_version }}
      - uses: actions/checkout@v4
      - run: make unit-tests

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: golangci/golangci-lint-action@v6.1.1
        with:
          version: 'v1.60'
          args: --timeout=${{ inputs.lint_timeout }}
