# Checkout repo and build a docker image.
# This action does not push any tags to the git repo, 
# it doesn't push the built image to ecr.
# This action is just to verify that image can be built with changes,
# proposed in a PR.
name: Verify Images Build

on:
  pull_request:
    branches:
      - 'master'

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-operator-image:
    uses: ./.github/workflows/_build-image.yml
    with:
      APP: operator
